# Site settings
title: domeµÄ¸öÈËÖ÷Ò³À²À²À²
email: text@gmail.com
description: ²âÊÔ²âÊÔ²âÊÔµÄblog# this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  Gaohaoyang
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

# highlight
# domepygments
# highlighter: pygments
# highlighter: rouge
# highlighter: false
