# Dependencies
kramdown:
  input: GFM
highlighter:      rouge

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
title:            注释线
tagline:          '话语是误会的源泉，所以我不想说给任何人听。我并不寄希望于有人会理解我。所有的这些，都是我在对自己说话。'
description:      '人们相互认识，但无法相互理解'
url:              http://shelldone.com

author:
  name:           'noteline'
  url:            https://github.com/noteline

paginate:         5



# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name : noteline
