auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: noteline
url: http://noteline.github.io
feed: /atom.xml
author_info: <a href="http://noteline.github.io/">noteline</a>
